# Generated by Django 3.2.9 on 2021-11-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('id_card_number', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(max_length=20)),
                ('sex', models.IntegerField()),
                ('nationality', models.CharField(max_length=20)),
            ],
        ),
    ]
